import React from 'react';
import { GitBranch, Shield, ArrowRight, Tag, ShieldAlert, Sparkles } from 'lucide-react';

export default function AttackPathViewer({ attackChains = [] }) {
  if (!attackChains || attackChains.length === 0 || !attackChains[0].nodes) {
    return null;
  }

  // Extract MITRE journey nodes generated by builder.py
  const chainData = attackChains[0];
  const allNodes = chainData.nodes || [];
  const mitreNodes = allNodes.filter(n => n.id && n.id.startsWith('mitre-'));
  const intelligence = chainData.intelligence;

  if (mitreNodes.length === 0) return null;

  return (
    <div className="bg-[var(--surface)] border border-[var(--border)] rounded-xl p-5 mb-6 shadow-sm">
      <div className="flex items-center justify-between mb-4 border-b border-[var(--border)] pb-3 flex-wrap gap-2">
        <div className="flex items-center space-x-2">
          <GitBranch className="w-5 h-5 text-[var(--danger)]" />
          <h3 className="text-xs font-bold text-[var(--text)] uppercase tracking-wider">
            Attack Journey & Intelligence Path
          </h3>
        </div>
        {intelligence && (
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-semibold px-2 py-0.5 rounded-full border border-[var(--danger-border)] bg-[var(--danger-bg)] text-[var(--danger)]">
              Risk: {intelligence.risk_score}/100 ({intelligence.severity})
            </span>
            <span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full border ${
              intelligence.confidence === 'High'
                ? 'border-[var(--brand)]/30 bg-[var(--brand)]/10 text-[var(--brand)]'
                : 'border-amber-500/30 bg-amber-500/10 text-amber-400'
            }`}>
              {intelligence.is_uncertain ? 'Uncertain / Low Confidence' : `${intelligence.confidence} Confidence`}
            </span>
          </div>
        )}
      </div>

      {intelligence?.explanation && (
        <div className="mb-4 bg-[var(--bg)] border border-[var(--border)] rounded-lg p-3 text-xs text-[var(--text)] flex items-start gap-2.5">
          <Sparkles className="w-4 h-4 text-[var(--brand)] shrink-0 mt-0.5" />
          <p className="leading-relaxed">{intelligence.explanation}</p>
        </div>
      )}

      <div className="flex flex-col items-center">
        {mitreNodes.map((node, i) => {
          // split label into title and subtitle (e.g. "Initial Access\n(T1190...)")
          const lines = (node.label || '').split('\n');
          const title = lines[0];
          const subtitle = lines.length > 1 ? lines[1] : null;
          const confText = node.confidence_score ? `${node.confidence_score}% (${node.confidence || node.confidence_level || 'High'})` : (node.confidence ? `${node.confidence} Conf` : null);

          return (
            <React.Fragment key={node.id}>
              <div className="w-full bg-[var(--surface-dark)] border border-[var(--border)] rounded-lg p-4 text-center">
                <div className="flex items-center justify-between mb-1">
                  <div className="font-bold text-[var(--danger)] text-sm">{title}</div>
                  <div className="flex items-center gap-1.5">
                    {confText && (
                      <span className="text-[10px] font-mono px-1.5 py-0.5 rounded border border-[var(--border)] bg-[var(--surface)] text-[var(--text-muted)]">
                        {confText}
                      </span>
                    )}
                    {node.cve && (
                      <span className="text-[10px] font-mono px-1.5 py-0.5 rounded border border-[var(--danger-border)] bg-[var(--danger-bg)] text-[var(--danger)]">
                        {node.cve}
                      </span>
                    )}
                  </div>
                </div>
                {subtitle && (
                  <div className="text-xs font-mono text-[var(--text-muted)] mb-2 text-left">{subtitle}</div>
                )}
                {node.evidence && (
                  <div className="mt-2 text-left bg-[var(--surface)] p-2.5 rounded border border-[var(--border)]">
                    <span className="block text-[10px] text-[var(--text-muted)] font-bold uppercase tracking-wider mb-1">
                      Verified Evidence
                    </span>
                    <span className="text-xs text-[var(--text)] font-mono whitespace-pre-wrap break-words leading-relaxed">
                      {typeof node.evidence === 'string' ? node.evidence.replace('Evidence:\n', '') : JSON.stringify(node.evidence)}
                    </span>
                  </div>
                )}
              </div>
              
              {i < mitreNodes.length - 1 && (
                <div className="py-2 text-[var(--text-muted)] text-sm font-bold">
                  ↓
                </div>
              )}
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
}

