import React, { useState, useEffect } from 'react';
import { getReport, getInvestigationStatus } from '../api/investigationService';
import EmptyState from '../components/EmptyState';
import { FileText, Download, ShieldAlert, FileSearch, Printer } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import Card from '../components/Card';
import SeverityChip from '../components/SeverityChip';
import FindingCard from '../components/FindingCard';
import { SEVERITY } from '../design/colors';
import { useTheme } from '../theme/useTheme';
import { ArrowDown } from 'lucide-react';

const SEV_COLORS = {
  Critical: '#DC2626',
  High:     '#EA580C',
  Medium:   '#D97706',
  Low:      '#2563EB',
  Info:     '#64748B',
};

export default function Reports() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const { resolved } = useTheme();

  useEffect(() => {
    let invId = localStorage.getItem('inv_id');
    if (invId === 'undefined' || invId === 'null') invId = null;
    if (!invId) { setLoading(false); return; }

    let intervalId = null;

    const loadData = async () => {
      try {
        const data = await getReport(invId);
        if (data && typeof data === 'object') {
          setReport(data);
          setError(null);

          const statusData = await getInvestigationStatus(invId).catch(() => null);
          if (statusData && statusData.isComplete) {
            if (intervalId) clearInterval(intervalId);
          }
        }
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    loadData();
    intervalId = setInterval(loadData, 2000);

    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  }, []);

  if (loading) {
    return (
      <div className="space-y-4">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-24 bg-[var(--bg)] border border-[var(--border)] rounded-xl animate-pulse" />
        ))}
      </div>
    );
  }

  if (error === 'no_inv') {
    return (
      <Card className="max-w-md text-center mx-auto mt-12">
        <FileSearch className="w-12 h-12 text-[var(--text-subtle)] mx-auto mb-3" />
        <h2 className="text-xl font-extrabold text-[var(--text)] mb-2">No report available</h2>
        <p className="text-sm text-[var(--text-muted)]">Complete an investigation to generate an executive report.</p>
      </Card>
    );
  }

  if (error) return <div className="p-8 text-[var(--danger)]">{error}</div>;

  return (
    <div className="space-y-6" id="sentinel-report-root">

      {/* ── Page header — hidden on print ── */}
      <div className="no-print">
        <PageHeader
          eyebrow="Reports"
          title="Executive investigation report"
          description="Generated by the Sentinel autonomous investigation engine."
        >
          {/* Print / Download PDF button */}
          <button
            onClick={() => window.print()}
            id="btn-download-pdf"
            className="inline-flex items-center gap-2 bg-[var(--text)] hover:opacity-90 text-[var(--surface)] px-4 py-2 rounded-lg text-sm font-semibold transition-colors shadow-sm"
          >
            <Printer className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
        </PageHeader>
      </div>

      {/* ── Risk summary banner — hidden on print (duplicated inside report body) ── */}
      <div className="no-print">
        <Card padding="p-6">
          <div className="flex items-center justify-between flex-wrap gap-6">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-xl bg-[var(--danger-bg)] border border-[var(--danger-border)] flex items-center justify-center">
                <ShieldAlert className="w-7 h-7 text-[var(--danger)]" />
              </div>
              <div>
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mb-1">Overall risk assessment</p>
                <p className="text-3xl font-extrabold text-[var(--text)]">{report?.overallRisk}</p>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-6 text-center">
              <div>
                <p className="text-2xl font-extrabold text-[var(--danger)]">{report?.criticalCount ?? 0}</p>
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">Critical</p>
              </div>
              <div>
                <p className="text-2xl font-extrabold text-[var(--warning)]">{report?.highCount ?? 0}</p>
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">High</p>
              </div>
              <div>
                <p className="text-2xl font-extrabold text-[var(--text)]">{report?.findingCount ?? 0}</p>
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">Total</p>
              </div>
            </div>
          </div>
        </Card>
      </div>

      {/* ════════════════════════════════════════════════
          PRINTABLE REPORT BODY
          Everything below this line is printed as-is.
          The sidebar / navbar are hidden via @media print.
      ════════════════════════════════════════════════ */}
      <div
        id="sentinel-printable-report"
        className="bg-[var(--surface)] border border-[var(--border)] rounded-xl shadow-sm overflow-hidden"
        style={{ WebkitPrintColorAdjust: 'exact', printColorAdjust: 'exact' }}
      >

        {/* ── Cover header band ── */}
        <div
          className="text-white p-8 flex justify-between items-center bg-print-dark report-page-header"
          style={{ backgroundColor: '#0F1B2D' }}
        >
          <div>
            <h2 className="text-2xl font-extrabold tracking-widest uppercase">SENTINEL</h2>
            <p className="text-[#94A3B8] text-xs mt-1 tracking-widest">Autonomous security investigation report — confidential</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-[#94A3B8]">Report date</p>
            <p className="text-sm font-semibold">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </div>

        <div className="p-10 space-y-10">

          {/* ── 1. Executive Summary ── */}
          <section className="report-section">
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--brand)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Executive summary</h3>
            </div>
            <p className="text-[var(--text)] leading-relaxed text-base">{report?.executiveSummary}</p>
          </section>

          {/* ── 2. Risk Assessment ── */}
          <section className="report-section">
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--danger)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Risk assessment</h3>
            </div>
            <div className="bg-[var(--bg)] border border-[var(--border)] rounded-lg p-5 flex items-center gap-6 flex-wrap report-card bg-print-light">
              <div className="text-center">
                <p className="text-4xl font-extrabold text-[var(--danger)]">{report?.overallRisk}</p>
                <p className="text-xs text-[var(--text-muted)] mt-1">Overall risk</p>
              </div>
              <div className="border-l border-[var(--border-strong)] pl-6 space-y-1.5">
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full" style={{ backgroundColor: SEV_COLORS.Critical }} />
                  {report?.criticalCount ?? 0} Critical severity findings
                </div>
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full" style={{ backgroundColor: SEV_COLORS.High }} />
                  {report?.highCount ?? 0} High severity findings
                </div>
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full" style={{ backgroundColor: '#64748B' }} />
                  {report?.findingCount ?? 0} Total findings identified
                </div>
              </div>
            </div>
          </section>

          {/* ── 3. Security Findings ── */}
          {report?.findings && report.findings.length > 0 && (
            <section className="report-section">
              <div className="flex items-center mb-4">
                <div className="w-1 h-6 bg-purple-500 rounded-full mr-3" />
                <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">
                  Correlated Security Findings ({report.findings.length})
                </h3>
              </div>
              <div className="space-y-4">
                {report.findings.map((f, idx) => (
                  <div key={idx} className="finding-card">
                    <FindingCard finding={f} />
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* ── 4. Attack Paths / MITRE Journey ── */}
          {report?.mitreJourney && report.mitreJourney.length > 0 && (
            <section className="report-section">
              <div className="flex items-center mb-4">
                <div className="w-1 h-6 bg-red-500 rounded-full mr-3" />
                <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">MITRE ATT&amp;CK journey</h3>
              </div>
              <div className="bg-[var(--surface-dark)] border border-[var(--border)] rounded-xl p-6 mitre-card">
                <div className="flex flex-col items-center">
                  {report.mitreJourney
                    .filter(n => n.evidence || n.id === 'mitre-start')
                    .map((node, idx, arr) => (
                      <React.Fragment key={node.id}>
                        <div className="bg-[var(--bg)] border border-[var(--border-strong)] p-4 rounded-lg w-full max-w-md text-center shadow-sm report-card">
                          <p className="font-bold text-[var(--text)] whitespace-pre-line text-sm">{node.label}</p>
                          {node.evidence && (
                            <div className="mt-3 pt-3 border-t border-[var(--border)] text-left text-xs">
                              <span className="font-bold text-gray-400 uppercase tracking-wider block mb-1">Evidence</span>
                              <p className="text-[var(--text-muted)] font-mono whitespace-pre-line">
                                {node.evidence.replace('Evidence:\n', '')}
                              </p>
                            </div>
                          )}
                        </div>
                        {idx < arr.length - 1 && (
                          <div className="py-2 text-[var(--border-strong)]">
                            <ArrowDown className="w-5 h-5" />
                          </div>
                        )}
                      </React.Fragment>
                    ))}
                </div>
              </div>
            </section>
          )}

          {/* ── 5. Remediation ── */}
          <section className="report-section">
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--success)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Recommended next steps</h3>
            </div>
            <ol className="list-decimal list-inside space-y-2 text-sm text-[var(--text)]">
              <li>Review the Remediation Center for prioritized, step-by-step remediation guidance.</li>
              <li>Address all Critical severity findings immediately before any High severity items.</li>
              <li>Validate remediations in a staging environment before applying to production.</li>
              <li>Re-run a Sentinel investigation after remediation to confirm the risk score has been reduced.</li>
            </ol>
          </section>

          {/* ── 6. Investigation Methodology ── */}
          <section className="report-section">
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--brand)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Investigation methodology</h3>
            </div>
            <p className="text-[var(--text)] leading-relaxed text-sm">
              This investigation was conducted using the Sentinel autonomous security pipeline. The scan was processed
              through a deterministic Rule Engine that applied {report?.findingCount ?? 'multiple'} security rules against
              the parsed scan data. Findings were enriched via the Knowledge Base with MITRE ATT&amp;CK techniques and CWE
              mappings, then scored by the Risk Engine, correlated by the Correlation Engine, and synthesized into attack
              chains. This summary was generated by the LLM module based solely on the deterministic findings.
            </p>
          </section>

          {/* ── Footer ── */}
          <div className="border-t border-[var(--border)] pt-6 text-center text-xs text-[var(--text-muted)]">
            Generated by Sentinel AI Security Investigation Engine v1.0.0 — {new Date().toISOString()}
          </div>

        </div>
      </div>
    </div>
  );
}
