import { useState, useEffect } from 'react';
import { getReport } from '../api/investigationService';
import { FileText, Download, ShieldAlert, FileSearch } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import Card from '../components/Card';
import SeverityChip from '../components/SeverityChip';
import { SEVERITY } from '../design/colors';
import { useTheme } from '../theme/useTheme';

// Print-only palette: Reports.jsx explicitly wants a fixed dark header band
// for the printed PDF, regardless of the user's current theme. We compute a
// readable tone from the active mode but it intentionally looks the same in
// light/dark when printed. App.css handles @media print overrides.
const riskColorCss = {
  Critical: 'var(--sev-critical)',
  High: 'var(--sev-high)',
  Medium: 'var(--sev-medium)',
  Low: 'var(--sev-low)',
  Info: 'var(--sev-info)',
};

export default function Reports() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const { resolved } = useTheme();
  const sevMode = resolved === 'dark' ? 'dark' : 'light';

  useEffect(() => {
    const invId = localStorage.getItem('inv_id');
    if (!invId) {
      setError('no_inv');
      setLoading(false);
      return;
    }
    getReport(invId)
      .then((data) => { setReport(data); setLoading(false); })
      .catch((err) => { setError(err.message); setLoading(false); });
  }, []);

  if (loading) {
    return (
      <div className="space-y-4">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-24 bg-[var(--bg)] border border-[var(--border)] rounded-xl animate-pulse" />
        ))}
      </div>
    );
  }

  if (error === 'no_inv') {
    return (
      <Card className="max-w-md text-center mx-auto mt-12">
        <FileSearch className="w-12 h-12 text-[var(--text-subtle)] mx-auto mb-3" />
        <h2 className="text-xl font-extrabold text-[var(--text)] mb-2">No report available</h2>
        <p className="text-sm text-[var(--text-muted)]">Complete an investigation to generate an executive report.</p>
      </Card>
    );
  }

  if (error) return <div className="p-8 text-[var(--danger)]">{error}</div>;

  // Pull the critical-tone accent for the inline display — falls back to CSS var.
  const critical = SEVERITY.Critical[sevMode];

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Executive investigation report"
        description="Generated by the Sentinel autonomous investigation engine."
      >
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 bg-[var(--text)] hover:opacity-90 text-[var(--surface)] px-4 py-2 rounded-lg text-sm font-semibold transition-colors shadow-sm"
        >
          <Download className="w-4 h-4" />
          <span>Download PDF</span>
        </button>
      </PageHeader>

      {/* Risk banner */}
      <Card padding="p-6">
        <div className="flex items-center justify-between flex-wrap gap-6">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-xl bg-[var(--danger-bg)] border border-[var(--danger-border)] flex items-center justify-center">
              <ShieldAlert className="w-7 h-7 text-[var(--danger)]" />
            </div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mb-1">Overall risk assessment</p>
              <p className="text-3xl font-extrabold text-[var(--text)]">
                {report.overallRisk}
              </p>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-6 text-center">
            <div>
              <p className="text-2xl font-extrabold text-[var(--danger)]">{report.criticalCount ?? 0}</p>
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">Critical</p>
            </div>
            <div>
              <p className="text-2xl font-extrabold text-[var(--warning)]">{report.highCount ?? 0}</p>
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">High</p>
            </div>
            <div>
              <p className="text-2xl font-extrabold text-[var(--text)]">{report.findingCount ?? 0}</p>
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-1">Total</p>
            </div>
          </div>
        </div>
      </Card>

      {/* Report body */}
      <div className="bg-[var(--surface)] border border-[var(--border)] rounded-xl shadow-sm overflow-hidden">
        {/* Print-faithful dark header band — literal so PDFs stay consistent
            regardless of which theme the user is viewing. */}
        <div
          className="text-white p-8 flex justify-between items-center"
          style={{ backgroundColor: '#0F1B2D' }}
        >
          <div>
            <h2 className="text-2xl font-extrabold tracking-widest uppercase">SENTINEL</h2>
            <p className="text-[#94A3B8] text-xs mt-1 tracking-widest">Autonomous security investigation report — confidential</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-[#94A3B8]">Report date</p>
            <p className="text-sm font-semibold">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </div>

        <div className="p-10 space-y-10">
          <section>
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--brand)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Executive summary</h3>
            </div>
            <p className="text-[var(--text)] leading-relaxed text-base">{report.executiveSummary}</p>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--danger)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Risk rating</h3>
            </div>
            <div className="bg-[var(--bg)] border border-[var(--border)] rounded-lg p-5 flex items-center gap-6 flex-wrap">
              <div className="text-center">
                <p className="text-4xl font-extrabold text-[var(--danger)]">{report.overallRisk}</p>
                <p className="text-xs text-[var(--text-muted)] mt-1">Overall risk</p>
              </div>
              <div className="border-l border-[var(--border-strong)] pl-6 space-y-1.5">
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full bg-[var(--danger)]" />
                  {report.criticalCount ?? 0} Critical severity findings
                </div>
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full bg-[var(--warning)]" />
                  {report.highCount ?? 0} High severity findings
                </div>
                <div className="flex items-center gap-2 text-sm text-[var(--text)]">
                  <span className="w-2 h-2 rounded-full bg-[var(--info)]" />
                  {report.findingCount ?? 0} Total findings identified
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--brand)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Investigation methodology</h3>
            </div>
            <p className="text-[var(--text)] leading-relaxed text-sm">
              This investigation was conducted using the Sentinel autonomous security pipeline. The scan was processed
              through a deterministic Rule Engine that applied {report.findingCount ?? 'multiple'} security rules against
              the parsed scan data. Findings were enriched via the Knowledge Base with MITRE ATT&CK techniques and CWE
              mappings, then scored by the Risk Engine, correlated by the Correlation Engine, and synthesized into attack
              chains. This summary was generated by the LLM module based solely on the deterministic findings.
            </p>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <div className="w-1 h-6 bg-[var(--success)] rounded-full mr-3" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-muted)]">Recommended next steps</h3>
            </div>
            <ol className="list-decimal list-inside space-y-2 text-sm text-[var(--text)]">
              <li>Review the Remediation Center for prioritized, step-by-step remediation guidance.</li>
              <li>Address all Critical severity findings immediately before any High severity items.</li>
              <li>Validate remediations in a staging environment before applying to production.</li>
              <li>Re-run a Sentinel investigation after remediation to confirm the risk score has been reduced.</li>
            </ol>
          </section>

          <div className="border-t border-[var(--border)] pt-6 text-center text-xs text-[var(--text-muted)]">
            Generated by Sentinel AI Security Investigation Engine v1.0.0 — {new Date().toISOString()}
          </div>
        </div>
      </div>
    </div>
  );
}
